# Generated by Django 5.2.8 on 2026-03-11 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(max_length=20, unique=True)),
                ('usa_dotacion', models.BooleanField(default=False)),
                ('usa_perfil_sociodemografico', models.BooleanField(default=False)),
                ('usa_capacitacion', models.BooleanField(default=False)),
                ('usa_asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('nombre_persona', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_expedicion', models.DateField()),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_telefono2', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('eps', models.CharField(blank=True, max_length=25, null=True)),
                ('pension', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('tipo_identificacion', 'numero_identificacion')},
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_archivo', models.CharField(choices=[('WORD', 'Documento Word'), ('EXCEL', 'Archivo Excel')], max_length=5)),
                ('archivo', models.FileField(upload_to='plantillas/')),
                ('es_global', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas', to='core.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plantilla')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_plantillas', to='core.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'plantilla')},
            },
        ),
    ]
