# Generated by Django 5.2.8 on 2026-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectoplantilla',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usa_asistencia',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usa_capacitacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usa_dotacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usa_perfil_sociodemografico',
        ),
        migrations.AlterField(
            model_name='proyectoplantilla',
            name='orden',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
