# Generated by Django 5.2.8 on 2026-01-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(choices=[('CIP', 'Ciprés'), ('TBC', 'Tribeca'), ('BV', 'Buena vista')], max_length=9, unique=True)),
                ('usa_dotacion', models.BooleanField(default=False)),
                ('usa_perfil_sociodemografico', models.BooleanField(default=False)),
                ('usa_capacitacion', models.BooleanField(default=False)),
                ('usa_asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('nombre_persona', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_expedicion', models.DateField()),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_telefono2', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('eps', models.CharField(blank=True, max_length=25, null=True)),
                ('pension', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('tipo_identificacion', 'numero_identificacion')},
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_archivo', models.CharField(choices=[('WORD', 'Documento Word'), ('EXCEL', 'Archivo Excel')], max_length=5)),
                ('archivo', models.FileField(upload_to='plantillas/')),
                ('activa', models.BooleanField(default=True)),
                ('proyectos', models.ManyToManyField(related_name='plantillas', to='core.proyecto')),
            ],
        ),
    ]
