# Generated by Django 5.2.8 on 2026-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proyectoplantilla_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoplantilla',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
