# Generated by Django 5.2.8 on 2026-01-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proyecto_persona_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='tipo_documento',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('dotacion', 'Dotación'), ('perfil', 'Perfil Sociodemográfico'), ('capacitacion', 'Capacitación'), ('asistencia', 'Asistencia')], default='Contrato', max_length=20),
            preserve_default=False,
        ),
    ]
