# Generated by Django 5.2.8 on 2026-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proyectoplantilla_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
