# Generated by Django 5.2.8 on 2026-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_plantilla_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plantilla',
            name='cargos',
            field=models.ManyToManyField(blank=True, help_text='Selecciona los cargos que deben firmar esta plantilla. Si lo dejas vacío, será una plantilla global para todos los cargos en este proyecto.', related_name='plantillas', to='core.cargo'),
        ),
    ]
